hmcts/pcq-backend

src/test/java/uk/gov/hmcts/pcq/DeleteMe.java
https://tools.hmcts.net/jira/browse/PCQ-30
Add a simple test to ensure the Jenkins pipeline does not fail.
```
[ ] Yes
[ ] No
```
=> Simple test for pipeline. To be removed

README.md, bin/init.sh, build.gradle, src/integrationTest/java/uk/gov/hmcts/reform/pcqbackend/config/SwaggerPublisher.java, src/integrationTest/java/uk/gov/hmcts/reform/pcqbackend/controllers/GetWelcomeTest.java, src/main/java/uk/gov/hmcts/reform/pcqbackend/Application.java, src/main/java/uk/gov/hmcts/reform/pcqbackend/config/SwaggerConfiguration.java, src/main/java/uk/gov/hmcts/reform/pcqbackend/controllers/RootController.java
https://tools.hmcts.net/jira/browse/PCQ-101
Refactored the PCQBackend project to remove demo reference and renamed the package. Updated the dependencies to use SpringBoot 2.5.5
```
[ ] Yes
[ ] No
```
=> Refactored the PCQBackend project

Jenkinsfile_CNP, Jenkinsfile_nightly, build.gradle, charts/pcq-backend/Chart.yaml, src/smokeTest/java/uk/gov/hmcts/reform/pcqbackend/DeleteMe.java
https://tools.hmcts.net/jira/browse/PCQ-101
```
[ ] Yes
[ ] No
```
=> Updated Chart.yml version field

.gitignore, infrastructure/aat.tfvars, infrastructure/main.tf, infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/PCQ-30
Setup terraform infrastructure
=> Infrastructure configuration

build.gradle
https://tools.hmcts.net/jira/browse/PCQ-54
```
[ ] Yes
[ X] No
```
=> Updated rest-assured version

.travis.yml, Jenkinsfile_nightly, src/main/java/uk/gov/hmcts/reform/pcqbackend/controllers/PcqAnswersController.java, src/security.sh
https://tools.hmcts.net/jira/browse/PCQ-44
```
[ ] Yes
[X ] No
```
=> pcq-44-Added security zap-api config

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/PCQ-114
```
[ ] Yes
[ X] No
```
=> PCQ-114-Updated pitest to version 1.4.6

.gitignore, Jenkinsfile_CNP, Jenkinsfile_nightly, build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/PCQ-37
```
[ ] Yes
[ X] No
```
=> pcq-37-functional-test-config-changes

Jenkinsfile_CNP, build.gradle
https://tools.hmcts.net/jira/browse/PCQ-47
```
[ ] Yes
[ X] No
```
=> pcq-47-added-reporting

src/integrationTest/resources/JsonSchema/submitAnswersSchema.json, src/integrationTest/resources/JsonTestFiles/DobSubmitAnswer.json, src/integrationTest/resources/JsonTestFiles/FirstSubmitAnswer.json, src/integrationTest/resources/JsonTestFiles/InvalidJson1.json, src/integrationTest/resources/JsonTestFiles/InvalidVersion.json, src/main/java/uk/gov/hmcts/reform/pcqbackend/domain/ProtectedCharacteristics.java, src/main/java/uk/gov/hmcts/reform/pcqbackend/model/PcqAnswerRequest.java, src/main/java/uk/gov/hmcts/reform/pcqbackend/model/PcqAnswerResponse.java, src/main/resources/JsonSchema/submitAnswersSchema.json, src/main/resources/db/migration/V003__Schema.sql, src/main/resources/uk/gov/hmcts/reform/pcqbackend/gitcommit/git.properties, src/test/resources/JsonSchema/submitAnswersSchema.json, src/test/resources/JsonTestFiles/DobSubmitAnswer.json, src/test/resources/JsonTestFiles/FirstSubmitAnswer.json, src/test/resources/JsonTestFiles/InvalidJson1.json, src/test/resources/JsonTestFiles/InvalidVersion.json
https://tools.hmcts.net/jira/browse/PCQ-162
```
[ ] Yes
[ X] No
```
=> Schema changes for case id, service id and actor

infrastructure/main.tf, infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/PCQ-145
Adding appinsights_instrumentation_key to pcq module.
```
[ ] Yes
[x] No
```
=> PCQ-145: Adding app insights variable to module.

src/functionalTest/java/uk/gov/hmcts/reform/pcqbackend/controllers/PcqAnswersErrorResponseTest.java, src/main/java/uk/gov/hmcts/reform/pcqbackend/controllers/PcqAnswersController.java, src/main/java/uk/gov/hmcts/reform/pcqbackend/exceptions/DataNotFoundException.java, src/test/java/uk/gov/hmcts/reform/pcqbackend/controllers/PcqAnswersControllerTest.java
https://tools.hmcts.net/jira/browse/PCQ-179
```
[ ] Yes
[X ] No
```
=> PCQ_179_Changed getAnswers not found response to 404

.env, Jenkinsfile_CNP, Jenkinsfile_nightly, build.gradle, charts/pcq-backend/Chart.yaml, charts/pcq-backend/values.yaml, config/owasp/suppressions.xml, docker-compose.yml, src/functionalTest/resources/JsonTestFiles/FirstSubmitAnswerWithCase.json, src/functionalTest/resources/application-functional.yaml, src/integrationTest/java/uk/gov/hmcts/reform/pcqbackend/util/PcqIntegrationTest.java, src/integrationTest/resources/application.yaml, src/main/java/uk/gov/hmcts/reform/pcqbackend/controllers/PcqAnswersController.java, src/main/java/uk/gov/hmcts/reform/pcqbackend/security/SecurityConfiguration.java, src/main/java/uk/gov/hmcts/reform/pcqbackend/service/SubmitAnswersService.java, src/main/java/uk/gov/hmcts/reform/pcqbackend/utils/ConversionUtil.java, src/main/resources/application.yaml, src/main/resources/bootstrap.yaml, src/test/java/uk/gov/hmcts/reform/pcqbackend/controllers/PcqAnswersControllerTest.java, src/test/java/uk/gov/hmcts/reform/pcqbackend/service/SubmitAnswersServiceTest.java
PCQ-119
```
[ ] Yes
[ X] No
```
=> PCQ-119 - PGP Encryption code added

charts/pcq-backend/Chart.yaml, charts/pcq-backend/values.demo.template.yaml
https://tools.hmcts.net/jira/browse/PCQ-145
Adding backend demo template.
```
[ ] Yes
[x] No
```
=> Pcq 145 add backend template

build.gradle, config/owasp/suppressions.xml, src/main/java/uk/gov/hmcts/reform/pcqbackend/config/TransformerColumnKeyLoader.java, src/main/java/uk/gov/hmcts/reform/pcqbackend/utils/ConversionUtil.java
PCQ-189
Updated the dependency versions as per the dependency report.
```
[ ] Yes
[ X] No
```
=> PCQ_189 Updated versions for the dependencies

Jenkinsfile_nightly
PCQ-46
The nightly build job configuration has been updated to send the security scan, functional test and mutation test reports to the functional-output folder.
```
[ ] Yes
[ X] No
```
=> PCQ_46 - Updated Jenkins Nightly file to push reports to functional-output folder

Jenkinsfile_CNP, charts/pcq-backend/Chart.yaml, charts/pcq-backend/values.perftest.template.yaml, config/owasp/suppressions.xml
PCQ_288
Added a perftest charts file and added resource limits there.
```
[ ] Yes
[X ] No
```
=> PCQ_288 - Increased container size for the perftest

Jenkinsfile_CNP, charts/pcq-backend/Chart.yaml, charts/pcq-backend/values.perftest.template.yaml, config/owasp/suppressions.xml
PCQ_288
Updated container sizing and removed deprecated installCharts
```
[ ] Yes
[ X] No
```
=> PCQ-288 - Updated container size for perftest and removed installCharts

Jenkinsfile_CNP, charts/pcq-backend/Chart.yaml, charts/pcq-backend/values.yaml, src/main/resources/application.yaml, src/main/resources/bootstrap.yaml
https://tools.hmcts.net/jira/browse/PCQ-329
Remove db username from charts config.
```
[ ] Yes
[x] No
```
=> PCQ-329 Updated to fix username issue.

charts/pcq-backend/Chart.yaml, charts/pcq-backend/values.perftest.template.yaml, charts/pcq-backend/values.yaml, config/owasp/suppressions.xml
PCQ-288
The recommended container sizes are now applied across all the environments. There was also a dependency check false positive that was failing nightly build and it is fixed here.
```
[ ] Yes
[ X] No
```
=> PCQ_288_ Added recommended container sizes for all environments

src/main/resources/bootstrap.yaml
https://tools.hmcts.net/jira/browse/PCQ-333
Update to correct application insights logging.
```
[ ] Yes
[x] No
```
=> PCQ-333: Fix app insights logging.

README.md, bin/set-pcq-docker-env.sh, docker-compose.yml
https://tools.hmcts.net/jira/browse/PCQ-522
Update documentation to run pcq-backend as a docker image. 
* Updated docker-compose.yaml file to pull correct image location.
* Added script to set environment values if not checking out branch.
* Updated readme with more updated instructions.
```
[ ] Yes
[x] No
```
=> PCQ-522 Run pcq-backend as docker.

config/owasp/suppressions.xml
PCQ-519
Spring boot upgrade and the False suppression fix.
```
[ ] Yes
[ X] No
```
=> PCQ519- Updated false suppression

charts/pcq-backend/Chart.yaml, charts/pcq-backend/values.yaml
https://tools.hmcts.net/jira/browse/PCQ-622
Update S2S URL
```
[ ] Yes
[x] No
```
=> PCQ-622 update S2S URL

Jenkinsfile_nightly, audit.json
Fix nightly build by adding missing environment variables.
```
[ ] Yes
[x] No
```
=> PCQ-1234: Fix nightly pipeline.

bin/idam-service-token.sh, src/functionalTest/resources/application-functional.yaml, src/integrationTest/java/uk/gov/hmcts/reform/pcqbackend/controllers/SasTokenControllerTest.java, src/integrationTest/resources/application.yaml, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/pcqbackend/controllers/SasTokenControllerTest.java, src/test/java/uk/gov/hmcts/reform/pcqbackend/security/AuthorisedServicesTest.java, src/test/java/uk/gov/hmcts/reform/pcqbackend/service/AuthServiceTest.java, src/test/resources/application.yaml
https://tools.hmcts.net/jira/browse/PCQ-622
Update to change authorised service to reform_scan_blob_router.
```
[ ] Yes
[x] No
```
=> PCQ-633 Update to change authorised service to reform_scan_blob_router

README.md, src/smokeTest/java/uk/gov/hmcts/reform/pcqbackend/smoke/SmokeTests.java
https://tools.hmcts.net/jira/browse/PCQ-637
Add smoke test for getAnswer endpoint.
```
[ ] Yes
[x] No
```
=> PCQ-637: Add smoke test for getAnswer endpoint

src/main/resources/application.properties
https://tools.hmcts.net/jira/browse/PCQ-646
Add db, disk space and hystrix to the readiness health group.
```
[ ] Yes
[x] No
```
=> PCQ-646: Add readiness check components

build.gradle, config/owasp/suppressions.xml, src/main/java/uk/gov/hmcts/reform/pcqbackend/security/SecurityConfiguration.java
PCQ-696
Removed health/readiness from the JWT monitor
Updated java plugin to 0.12.0
```
[ ] Yes
[ X] No
```
=> PCQ-696 - Updated java plugin and removed health/readiness from jwt monitor

infrastructure/aat.tfvars, infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/PCQ-651
Remove old MI
```
[ ] Yes
[x] No
```
=> PCQ-651: Remove old MI

infrastructure/aat.tfvars, infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/PCQ-651
Merging master changes to demo.
```
[ ] Yes
[x] No
```
=> PCQ-651 Merge terraform changes to demo

build.gradle, src/integrationTest/java/uk/gov/hmcts/reform/pcqbackend/util/PcqBackEndClient.java, src/main/java/uk/gov/hmcts/reform/pcqbackend/controllers/ConsolidationController.java, src/main/java/uk/gov/hmcts/reform/pcqbackend/model/PcqRecordWithoutCaseResponse.java, src/main/java/uk/gov/hmcts/reform/pcqbackend/model/PcqWithoutCaseResponse.java, src/main/java/uk/gov/hmcts/reform/pcqbackend/service/SubmitAnswersService.java, src/test/java/uk/gov/hmcts/reform/pcqbackend/controllers/ConsolidationControllerTest.java, src/test/java/uk/gov/hmcts/reform/pcqbackend/controllers/PcqAnswersControllerTest.java, src/test/java/uk/gov/hmcts/reform/pcqbackend/controllers/SasTokenControllerTest.java, src/test/java/uk/gov/hmcts/reform/pcqbackend/security/AuthorisedServicesTest.java, src/test/java/uk/gov/hmcts/reform/pcqbackend/security/JwtTokenFilterTest.java, src/test/java/uk/gov/hmcts/reform/pcqbackend/service/AuthServiceTest.java, src/test/java/uk/gov/hmcts/reform/pcqbackend/service/ConsolidationServiceTest.java, src/test/java/uk/gov/hmcts/reform/pcqbackend/service/SasTokenServiceTest.java, src/test/java/uk/gov/hmcts/reform/pcqbackend/service/SubmitAnswersServiceTest.java, src/test/java/uk/gov/hmcts/reform/pcqbackend/util/FlywayNoOpStrategyTest.java
https://tools.hmcts.net/jira/browse/PCQ-689
Update to clear most of the sonarcloud issues including eliminating all blocker and critical issues.
```
[ ] Yes
[x] No
```
=> PCQ-689 Updated to address sonarcloud issues.

src/main/java/uk/gov/hmcts/reform/pcqbackend/repository/ProtectedCharacteristicsRepository.java, src/main/java/uk/gov/hmcts/reform/pcqbackend/repository/ProtectedCharacteristicsRepositoryCustom.java, src/main/java/uk/gov/hmcts/reform/pcqbackend/repository/impl/ProtectedCharacteristicsRepositoryImpl.java, src/main/java/uk/gov/hmcts/reform/pcqbackend/service/SubmitAnswersService.java, src/test/java/uk/gov/hmcts/reform/pcqbackend/controllers/PcqAnswersControllerTest.java, src/test/java/uk/gov/hmcts/reform/pcqbackend/service/SubmitAnswersServiceTest.java
PCQ718
Added method "persist" to the repository which will prevent the duplicate GET call.
```
[ ] Yes
[X ] No
```
=> PCQ718 - Added new method to persist record

bin/set-pcq-docker-env.sh, build.gradle, config/owasp/suppressions.xml, docker-compose.yml
https://tools.hmcts.net/jira/browse/PCQ-740
Update to docker script to add frontend and service-auth components and update to build.grade to fix vulnerabilities in build.
```
[ ] Yes
[x] No
```
=> PCQ-740: Fixing nightly build and updaing docker script.

build.gradle
https://tools.hmcts.net/jira/browse/PCQ-745
Nightly build fix for the dependency check error.
```
[ ] Yes
[ X] No
```
=> PCQ-745_Fix CVE-2020-28052

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/PCQ-757
Minor update to upgrade postgreSQL library.
```
[ ] Yes
[x] No
```
=> PCQ-757: Upgrade postgreSQL library.

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/PCQ-757
Update to upgrade Spring boot and resolve some older suppressions.
```
[ ] Yes
[x] No
```
=> PCQ-758: Update to upgrade springboot.

Jenkinsfile_CNP, build.gradle, config/owasp/suppressions.xml, src/integrationTest/java/uk/gov/hmcts/reform/pcqbackend/controllers/TestContainerDbTest.java
https://tools.hmcts.net/jira/browse/PCQ-767
Test and fix mutation test mutation tests and security scan. Note looks like both were failing because of the testcontainer using an unavailable postgres image.
```
[ ] Yes
[x] No
```
=> PCQ-767-Fix Nightly Build

src/functionalTest/java/uk/gov/hmcts/reform/pcqbackend/controllers/SasTokenControllerTest.java, src/integrationTest/java/uk/gov/hmcts/reform/pcqbackend/controllers/SasTokenControllerTest.java, src/main/java/uk/gov/hmcts/reform/pcqbackend/service/SasTokenService.java, src/test/java/uk/gov/hmcts/reform/pcqbackend/service/SasTokenServiceTest.java
https://tools.hmcts.net/jira/browse/PCQ-791
Update to give BSP team read access to stream PCQ Blobs to the Blob Storage container.
```
[ ] Yes
[x] No
```
=> PCQ-791 Update to add read permission for BSP to stream blobs.

charts/pcq-backend/Chart.yaml
https://tools.hmcts.net/jira/browse/PCQ-781
Update helm charts to 3.4.4
```
[ ] Yes
[x] No
```
=> PCQ-781: Update helm charts version

src/integrationTest/java/uk/gov/hmcts/reform/pcqbackend/controllers/SasTokenControllerTest.java
https://tools.hmcts.net/jira/browse/PCQ-1234
Fix to integration test run an hour before midnight.
```
[ ] Yes
[x] No
```
=> PCQ-1234 Fix to integration test run an hour before midnight.

build.gradle, src/functionalTest/java/uk/gov/hmcts/reform/pcqbackend/controllers/SasTokenControllerTest.java, src/integrationTest/java/uk/gov/hmcts/reform/pcqbackend/controllers/SasTokenControllerTest.java, src/test/java/uk/gov/hmcts/reform/pcqbackend/service/SasTokenServiceTest.java
https://tools.hmcts.net/jira/browse/PCQ-807
Update to use latest netty libraries to remove code vulnerbility.
```
[ ] Yes
[x] No
```
=> PCQ-807 Updating to use latest netty library.

build.gradle
https://tools.hmcts.net/jira/browse/PCQ-814
Fix to vulnerability in code.
```
[ ] Yes
[x] No
```
=> PCQ-814: Fix to vulnerability in tomcat.

build.gradle
https://tools.hmcts.net/jira/browse/PCQ-830
Fix vulnerability with netty library.
```
[ ] Yes
[x] No
```
=> PCQ-830: Fix vulnerability

build.gradle
https://tools.hmcts.net/jira/browse/PCQ-838
CVE fix - Updated Netty version to 4.1.61
```
[ ] Yes
[ X] No
```
=> PCQ838 - Updated netty version to 4.1.61

charts/pcq-backend/Chart.yaml
https://tools.hmcts.net/jira/browse/PCQ-840
Helm charts version upgrade.
```
[ ] Yes
[x] No
```
=> PCQ-840 Updated charts version.

build.gradle
https://tools.hmcts.net/jira/browse/PCQ-843
Update to address CVE in commons-io.
```
[ ] Yes
[x] No
```
=> PCQ-843: Update to address CVE in Backend

build.gradle, gradle/wrapper/gradle-wrapper.properties, src/functionalTest/java/uk/gov/hmcts/reform/pcqbackend/controllers/SasTokenControllerTest.java
https://tools.hmcts.net/jira/browse/PCQ-858
Fix to SAS test which appear to fail intermitantly and don't run locally.
```
[ ] Yes
[x] No
```
=> PCQ-858: Logging change.

security.sh
https://tools.hmcts.net/jira/browse/PCQ-872
Fix ZAP security nightly build script issues
```
[ ] Yes
[x] No
```
=> Nightly dev

Jenkinsfile_nightly, build.gradle, config/fortify-client.properties, security.sh
https://tools.hmcts.net/jira/browse/PCQ-880
Fortify integration.
```
[ ] Yes
[x] No
```
=> PCQ-880: Updated to add fortify pipeline

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/PCQ-1024
Changed two file build.gradle and suppression.xml to fix vulnerability for spring and jakarta
```
[ ] Yes
[x] No
```
=> pcq backend vulnerability fix

Jenkinsfile_CNP
https://tools.hmcts.net/jira/browse/PCQ-988
This change is about sync Other Branches with master if any change happens in master
```
[ ] Yes
[x] No
```
=> sync Other Branches with Master

build.gradle, src/functionalTest/java/uk/gov/hmcts/reform/pcqbackend/controllers/OptOutPcqAnswersTest.java, src/functionalTest/java/uk/gov/hmcts/reform/pcqbackend/controllers/PcqBaseFunctionalTest.java, src/functionalTest/resources/JsonSchema/answer_definitions_schema.json, src/integrationTest/java/uk/gov/hmcts/reform/pcqbackend/controllers/OptOutPcqRequestTest.java, src/integrationTest/java/uk/gov/hmcts/reform/pcqbackend/util/PcqIntegrationTest.java, src/integrationTest/resources/JsonSchema/answer_definitions_schema.json, src/main/java/uk/gov/hmcts/reform/pcqbackend/domain/ProtectedCharacteristics.java, src/main/java/uk/gov/hmcts/reform/pcqbackend/repository/ProtectedCharacteristicsRepository.java, src/main/java/uk/gov/hmcts/reform/pcqbackend/service/SubmitAnswersService.java, src/main/java/uk/gov/hmcts/reform/pcqbackend/utils/ConversionUtil.java, src/main/resources/JsonSchema/answer_definitions_schema.json, src/main/resources/db/migration/V006__Schema.sql, src/test/java/uk/gov/hmcts/reform/pcqbackend/controllers/PcqAnswersControllerTest.java, src/test/java/uk/gov/hmcts/reform/pcqbackend/service/SubmitAnswersServiceTest.java, src/test/resources/JsonSchema/answer_definitions_schema.json, src/test/resources/JsonTestFiles/FirstSubmitAnswerOptOut.json
https://tools.hmcts.net/jira/browse/PCQ-984
This change is for PCQ-Backend for  to set optout flag in backend when the optout is true, instead of deleting the record.
```
[ ] Yes
[x] No
```
=> PCQ-984 set Optout flag Pcq backend

infrastructure/state.tf
https://tools.hmcts.net/jira/browse/PCQ-984
Terraform fix
```
[ ] Yes
[x] No
```
=> Pcq-984 Terraform Script fix

src/main/java/uk/gov/hmcts/reform/pcqbackend/repository/ProtectedCharacteristicsRepository.java, src/main/java/uk/gov/hmcts/reform/pcqbackend/service/ConsolidationService.java, src/test/java/uk/gov/hmcts/reform/pcqbackend/controllers/ConsolidationControllerTest.java, src/test/java/uk/gov/hmcts/reform/pcqbackend/service/ConsolidationServiceTest.java
https://tools.hmcts.net/jira/browse/PCQ-985
This change is about when trying to consolidate we just need to consider those records where ccdId is null and optout is false.
```
[ ] Yes
[X] No
```
=> PCQ-985 Optout for Consolidation

build.gradle
https://tools.hmcts.net/jira/browse/PCQ-1117
This change it to fix dependency check 
```
[ ] Yes
[x] No
```
=> PCQ-1117 Backend dependency check Fixed

README.md
https://tools.hmcts.net/jira/browse/PCQ-1129
Corrected minor spelling mistakes in README.md
**Does this PR introduce a breaking change?**
```
[ ] Yes
[x] No
```
=> PCQ-1129: Adding update to README.md

build.gradle, src/main/java/uk/gov/hmcts/reform/pcqbackend/config/SwaggerConfiguration.java, src/main/java/uk/gov/hmcts/reform/pcqbackend/controllers/ConsolidationController.java, src/main/java/uk/gov/hmcts/reform/pcqbackend/controllers/PcqAnswersController.java, src/main/java/uk/gov/hmcts/reform/pcqbackend/controllers/SasTokenController.java
https://tools.hmcts.net/jira/browse/PCQ-1113
Added high level documentation to the PCQ backend API and tagged end-points
[ ] Yes
[x] No
=> PCQ-1113 High level documentation to API and end-points tagging

Jenkinsfile_nightly
https://tools.hmcts.net/jira/browse/PCQ-1190
This change is to disable Fortify scan on Backend
```
[ ] Yes
[x] No
```
=> PCQ-1190 Disable Fortify Scan for backend

build.gradle
https://tools.hmcts.net/jira/browse/PCQ-1195
This change is to upgrade log4j to 2.15.0
```
[ ] Yes
[x] No
```
=> PCQ-1195 log4j upgrade

Jenkinsfile_nightly
https://tools.hmcts.net/jira/browse/PCQ-1212
This change to Enable fortify back again after account is unlocked
```
[ ] Yes
[x] No
```
=> PCQ-1212 Enable Fortify scan

build.gradle, gradle/wrapper/gradle-wrapper.properties
https://tools.hmcts.net/jira/browse/PCQ-1134
Update pcq-backend to Gradle 7.2
Summary of issues fixed :-
**Error:**	Could not set unknown property 'configDir' for extension 'checkstyle' of type org.gradle.api.plugins.quality.CheckstyleExtension.
**Fix:**	Replace 'configDir' with 'configDirectory'
**Error:** 	Could not find method compile() ...
**Fix:**	Replace 'compile' with 'implementation'		(in dependencies block)
Replace 'estCompile' with 'estImplementation'	(throughout build.gradle)
**Error:**	Entry xxxxxxxx is a duplicate but no duplicate handling strategy has been set.
**Fix:**	Add rootProject.tasks.named .... duplicatesStrategy = 'include'
**Does this PR introduce a breaking change?**
```
[ ] Yes
[x] No
```
=> PCQ‐1134: Update pcq-backend to Gradle 7.2

build.gradle, gradle/wrapper/gradle-wrapper.properties
=> Revert "PCQ‐1134: Update pcq-backend to Gradle 7.2"

src/main/java/uk/gov/hmcts/reform/pcqbackend/controllers/PcqAnswersController.java
https://tools.hmcts.net/jira/browse/PCQ-1241
Hide Delete endpoint from swagger documentation
[ ] Yes
[X] No
=> PCQ-1241 Ignoring Delete endpoint from swagger documentation

build.gradle
https://tools.hmcts.net/jira/browse/PCQ-1236
This change is regarding hmcts library upgrade
```
[ ] Yes
[x] No
```
=> PCQ-1236 hmcts library update

build.gradle
https://tools.hmcts.net/jira/browse/PCQ-1338
This change is about dependency fix
```
[ ] Yes
[X] No
```
=> Pcq 1338 dependency check

Jenkinsfile_nightly
https://tools.hmcts.net/jira/browse/PCQ-816
This change is to revert the docker image to latest not zapTesting one
```
[ ] Yes
[x] No
```
=> Reverting to latest Imagae

build.gradle
https://tools.hmcts.net/jira/browse/PCQ-959
This change is to upgrade Jackson packages
```
[ ] Yes
[x] No
```
=> PCQ-959 Jackson packages upgrade

build.gradle
https://tools.hmcts.net/jira/browse/PCQ-1426
Fix for jackson-databind-2.13.2 dependency check , CVE-2020-36518.
**Does this PR introduce a breaking change?**
```
[ ] Yes
[x] No
```
=> PCQ-1426 Dependency-check-jackson-databind

build.gradle
https://tools.hmcts.net/jira/browse/PCQ-961
This change is to upgrade Library for flyway-core, flwaydb and PostgreSQL as identified by [dependabot-preview]
```
[ ] Yes
[x] No
```
=> PCQ-961 upgrade Flywayand Postgresql

build.gradle
https://tools.hmcts.net/jira/browse/PCQ-962
This change is about upgrading some libraries
```
[ ] Yes
[x] No
```
=> PCQ-962 Upgrade libraries

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/PCQ-1452
Update to springframework.boot 2.5.12 and suppress spring-plugin vulnerabilities.
```
[ ] Yes
[x] No
```
=> PCQ-1452: Suppress vulnerability with spring-plugin.

security.sh
https://tools.hmcts.net/jira/browse/PCQ-968
This change is to fix security scan
```
[ ] Yes
[x] No
```
=> PCQ-968 Security scan fix

build.gradle, config/pmd/ruleset.xml, src/integrationTest/resources/application.properties, src/main/java/uk/gov/hmcts/reform/pcqbackend/config/SwaggerConfiguration.java, src/main/resources/application.properties
https://tools.hmcts.net/jira/browse/PCQ-1333
This change is to upgrade spring boot and spring cloud
```
[ ] Yes
[x] No
```
=> PCQ-1333 Spring Framework Update

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/PCQ-790
This change is to fix spring-security dependency fix.
```
[ ] Yes
[x] No
```
=> PCQ-790 Dependency Check fix

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/PCQ-876
Changes has been made to fix dependency check.
```
[ ] Yes
[x] No
```
=> PCQ-876 Dependency check fix

renovate/configure/renovate.json
https://tools.hmcts.net/jira/browse/PCQ-1335
This change is to configure renovate
```
[ ] Yes
[x] No
```
=> PCQ-1335 Configuring Renovate in PCQ-backend

build.gradle, charts/pcq-backend/Chart.yaml, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/PCQ-941
This change is to fix Dependency check.
```
[ ] Yes
[x] No
```
=> PCQ-941 Dependency check fixed

.github/dependabot.yml
https://tools.hmcts.net/jira/browse/PCQ-896
This is to configure dependabot
```
[ ] Yes
[x] No
```
=> PCQ-896 upgrading dependabot

build.gradle
https://tools.hmcts.net/jira/browse/PCQ-937
This change is to upgrade springframework libraries
```
[ ] Yes
[x] No
```
=> PCQ-937 upgrade spring framework libraries

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/PCQ-1456
This change is to fix Dependency check
```
[ ] Yes
[x] No
```
=> PCQ-1456 dependency check fixed

build.gradle
https://github.com/hmcts/pcq-backend/pull/new/pcq-937
This change is to upgrade libraries
```
[ ] Yes
[x] No
```
=> More Libraries upgrade

build.gradle
https://tools.hmcts.net/jira/browse/PCQ-937
libraries upgrade
```
[ ] Yes
[x] No
```
=> PCQ-937 more library upgrades

build.gradle, src/functionalTest/resources/application-functional.yaml, src/integrationTest/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/pcqbackend/security/AuthorisedServicesTest.java, src/test/resources/application.yaml
https://tools.hmcts.net/jira/browse/PCQ-1466
This change is to upgrade Flyway from 7.15.0 to 8.5.13
```
[ ] Yes
[x] No
```
=> PCQ-1466 Flyway upgrade to 8.5.13

build.gradle
https://tools.hmcts.net/jira/browse/PCQ-1535
This change is to fix dependency check for snakeyml
```
[ ] Yes
[x] No
```
=> PCQ-1535 dependency check fix

Jenkinsfile_nightly
https://tools.hmcts.net/jira/browse/PCQ-1536
This change is disable nightly build during weekend
```
[ ] Yes
[x] No
```
=> PCQ-1536 disable nightly build during weekend

build.gradle
https://tools.hmcts.net/jira/browse/PCQ-1596
This change is to fix Dependency check related to spring-security and tomcat-embed
```
[ ] Yes
[x] No
```
=> PCQ-1596 dependency cheeck fix

README.md
https://tools.hmcts.net/jira/browse/PCQ-1593
Add Sonar Badges and Overview section
```
[ ] Yes
[x] No
```
=> PCQ-1593 Add Sonar Badges and Overview

build.gradle
https://tools.hmcts.net/jira/browse/PCQ-1600
This change is about upgrading libraries
```
[ ] Yes
[x] No
```
=> PCQ-1600 Library upgrade

build.gradle, charts/pcq-backend/Chart.yaml
https://tools.hmcts.net/jira/browse/PCQ-1600
This change is to upgrade libraries
```
[ ] Yes
[x] No
```
=> PCQ-1600 libraries upgrade

build.gradle
https://tools.hmcts.net/jira/browse/PCQ-1600
This change is about upgrading libraries
```
[ ] Yes
[x] No
```
=> PCQ-1600 Upgarding libraries

build.gradle
https://tools.hmcts.net/jira/browse/PCQ-1613
Update postgresql library.
```
[ ] Yes
[x] No
```
=> PCQ-1613: Update postgresql library.

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/PCQ-1620
This change is to fix CVE-2021-37533
```
[ ] Yes
[x] No
```
=> PCQ-1620 dependency fix

build.gradle, charts/pcq-backend/Chart.yaml
https://tools.hmcts.net/jira/browse/PCQ-1626
This change is to fix CVE-2022-41881, CVE-2022-41915
```
[ ] Yes
[x] No
```
=> PCQ-1626 Dependency check fix

Jenkinsfile_CNP, build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/PCQ-1627
This change is to fix CVE-2021-4277.
```
[ ] Yes
[x] No
```
=> PCQ-1627 Removing library

build.gradle
https://tools.hmcts.net/jira/browse/PCQ-1631
This change is to fix CVE-2022-45143
```
[ ] Yes
[x] No
```
=> PCQ-1631 dependency check fix

Jenkinsfile_nightly, build.gradle
https://tools.hmcts.net/jira/browse/PCQ-1639
Changing After to AfterAlways
```
[ ] Yes
[x] No
```
=> PCQ-1639 chaging after

build.gradle
https://tools.hmcts.net/jira/browse/PCQ-1622
This change is to fix mutation test
```
[ ] Yes
[x] No
```
=> PCQ-1622 mutation test fix

.github/dependabot.yml, build.gradle, charts/pcq-backend/Chart.yaml
https://tools.hmcts.net/jira/browse/PCQ-1648
Configuring dependatbot to run on Thursday at 6:00pm.
```
[ ] Yes
[x] No
```
=> PCQ-1648 configuring dependabot for particular day

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/PCQ-1659
This change is to suppress CVE-2022-1471
```
[ ] Yes
[x] No
```
=> PCQ-1659 suppress CVE-2022-1471

build.gradle
Spring Framework CVE-2023-20861 fix
```
[ ] Yes
[x] No
```
=> Spring framework cve-2023-20861 fix

build.gradle
https://tools.hmcts.net/jira/browse/PCQ-1718
Libarry upgrade for spring framework
```
[ ] Yes
[x] No
```
=> Upgrade springBoot Library

build.gradle
https://tools.hmcts.net/jira/browse/PCQ-1723
Fix  CVE-2023-20873
```
[ ] Yes
[x] No
```
=> PCQ-1723 CVE-2023-20873 fix

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/PCQ-1749
This change is to suppress CVE-2023-20883
```
[ ] Yes
[x] No
```
=> PCQ-1749 suppress CVE-2023-20883

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/PCQ-1757
This change is to suppress CVE-2023-35116
```
[ ] Yes
[x] No
```
=> PCQ-1757 suppress CVE-2023-35116

build.gradle
This change is on back of dependabot PR for flyway upgrade . Running this on nightly-dev gave issue about jaxb-bind. Adding that library
```
[ ] Yes
[x] No
```
=> flyway-upgrade

build.gradle, src/main/java/uk/gov/hmcts/reform/pcqbackend/security/SecurityConfiguration.java
https://tools.hmcts.net/jira/browse/PCQ-1783
address CVE-2023-34035
```
[ ] Yes
[x] No
```
=> PCQ-1783 address CVE-2023-34035

src/functionalTest/java/uk/gov/hmcts/reform/pcqbackend/controllers/PcqRecordWithoutCaseTest.java, src/functionalTest/resources/application-functional.yaml, src/main/resources/application.yaml
This change is to change the config from 90 days to 120 days to consider consolidation cases
```
[ ] Yes
[x] No
```
=> PCQ-1782 changing config to 120 days

src/functionalTest/java/uk/gov/hmcts/reform/pcqbackend/controllers/PcqRecordWithoutCaseTest.java, src/functionalTest/resources/application-functional.yaml, src/main/resources/application.yaml
This is to change config to 150 days
```
[ ] Yes
[x] No
```
=> PCQ-1782 changing config to 150 days

src/functionalTest/java/uk/gov/hmcts/reform/pcqbackend/controllers/PcqRecordWithoutCaseTest.java, src/functionalTest/resources/application-functional.yaml, src/main/resources/application.yaml
Changing config to 180 days
```
[ ] Yes
[x] No
```
=> PCQ-1782 changing config to 180 days

src/functionalTest/java/uk/gov/hmcts/reform/pcqbackend/controllers/PcqBaseFunctionalTest.java, src/functionalTest/java/uk/gov/hmcts/reform/pcqbackend/controllers/PcqRecordWithoutCaseTest.java, src/functionalTest/resources/application-functional.yaml, src/main/resources/application.yaml
This change is to change config to 210 days
```
[ ] Yes
[x] No
```
=> PCQ-1782 changing config to 210

src/functionalTest/resources/application-functional.yaml, src/main/resources/application.yaml
Changing config to 240 days
```
[ ] Yes
[x] No
```
=> PCQ-1782 changing config to 240 days

src/functionalTest/resources/application-functional.yaml, src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/LAU-710
This is to change config to 270 days
```
[ ] Yes
[x] No
```
=> PCQ-1782 changing config to 270

src/functionalTest/resources/application-functional.yaml, src/main/resources/application.yaml
This will change config to 300
```
[ ] Yes
[x] No
```
=> PCQ-1782 config to 300 days

src/functionalTest/resources/application-functional.yaml, src/main/resources/application.yaml
Change the config to 330
```
[ ] Yes
[x] No
```
=> PCQ-1782 changing config to 330

audit.json
https://tools.hmcts.net/jira/browse/PCQ-1804
Security scan fix
```
[ ] Yes
[x] No
```
=> PCQ-1804 security scan fix

audit.json
https://tools.hmcts.net/jira/browse/PCQ-1804
This change is to fix security scan
```
[ ] Yes
[x] No
```
=> PCQ-1804 fix security scan

build.gradle
https://tools.hmcts.net/jira/browse/PCQ-1807
This change is to fix CVE-2023-41080
```
[ ] Yes
[x] No
```
=> PCQ-1807 tomcat upgrade for CVE-2023-41080

.github/renovate.json
https://tools.hmcts.net/jira/browse/PCQ-1806
Changing renovate configuration
```
[ ] Yes
[x] No
```
=> PCQ-1806 changing renovate config

src/functionalTest/resources/application-functional.yaml, src/main/resources/application.yaml
Changing config to 90 days
```
[ ] Yes
[x] No
```
=> PCQ-1782 changing config to 90 days

src/functionalTest/resources/application-functional.yaml, src/main/resources/application.yaml
Change config to 300
```
[ ] Yes
[x] No
```
=> PCQ-1782 changing config to 300

src/functionalTest/resources/application-functional.yaml, src/main/resources/application.yaml
Change config back to 90
```
[ ] Yes
[x] No
```
=> PCQ-1782 reverting to 90

Jenkinsfile_CNP
Remove enableCleanupOfHelmReleaseOnSuccess
```
[ ] Yes
[x] No
```
=> Remove enableCleanupOfHelmReleaseOnSuccess

build.gradle, charts/pcq-backend/Chart.yaml, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/PCQ-1809
upgrading chart version
```
[ ] Yes
[x] No
```
=> PCQ-1809 upgrading charts for pcq-backend

lib/applicationinsights.json
https://tools.hmcts.net/jira/browse/PCQ-1750
This change is to log only 1% of health message
```
[ ] Yes
[x] No
```
=> PCQ-1750 Log 1% of health message

config/owasp/suppressions.xml, infrastructure/main.tf
Add read-only user permissions - see https://hmcts-reform.slack.com/archives/CA4F2MAFR/p1698748889478269
```
[ ] Yes
[x] No
```
=> Add read only user permissions

infrastructure/sdp.tf
Attempt to use SDP user module to create SDP read only user in PCQ backend postgresql flex database.
=> Add sdp read only user

build.gradle
https://tools.hmcts.net/jira/browse/PCQ-1849
This change is to fix CVE-2023-34053 and CVE-2023-34055 and upgrade spring framework
```
[ ] Yes
[x] No
```
=> PCQ-1849 spring framework upgrade

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/PCQ-1843
This change is remove suppression for cve-2023-4586 and upgrade logback
```
[ ] Yes
[x] No
```
=> PCQ-1843 fix cve-2023-4586 and upgrade logback

build.gradle, charts/pcq-backend/values.yaml, infrastructure/main.tf, infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/PCQ-1835
Update infrastructure to take new values
```
[ ] Yes
[x] No
```
=> Pcq 1835 prepare infrastructure to use new flexible value for future migration

infrastructure/main.tf
https://tools.hmcts.net/jira/browse/PCQ-1838
Remove single server db module for PCQ
```
[ ] Yes
[x] No
```
=> PCQ-1838 remove singer server db module

infrastructure/main.tf
https://tools.hmcts.net/jira/browse/PCQ-1838
This change to remove resources
```
[ ] Yes
[x] No
```
=> Adding feature

infrastructure/main.tf
https://tools.hmcts.net/jira/browse/PCQ-1838
Remove added feature
```
[ ] Yes
[x] No
```
=> PCQ-1838 remove added feature

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/PCQ-1856
This change is to suppress CVE-2023-36052 till 1st April 2024 as no fix available
```
[ ] Yes
[x] No
```
=> PCQ-1856 extending time on CVE-2023-36052

build.gradle
Bump junit plugin version for pitest
=> fix pitest

audit.json
Suppression some url raised by security scan
```
[ ] Yes
[x] No
```
=> PCQ-Backend suppression

charts/pcq-backend/Chart.yaml, charts/pcq-backend/values.yaml
https://tools.hmcts.net/jira/browse/PCQ-1878
Enable spotInstance
```
[ ] Yes
[x] No
```
=> Enable spotInstances

build.gradle, charts/pcq-backend/values.yaml, infrastructure/state.tf
https://tools.hmcts.net/jira/browse/PCQ-1880
Enable autoscaling
```
[ ] Yes
[x] No
```
=> PCQ-1880 EnableautoScaling

charts/pcq-backend/Chart.yaml, charts/pcq-backend/values.yaml
https://tools.hmcts.net/jira/browse/PCQ-1880
Change maxReplicas to 2 for lower environments
```
[ ] Yes
[x] No
```
=> PCQ-1880 maxReplica set to 2 for lower env

charts/pcq-backend/Chart.yaml, charts/pcq-backend/values.yaml
https://tools.hmcts.net/jira/browse/PCQ-1880
Changing Memory requests and memory Limit
```
[ ] Yes
[x] No
```
=> PCQ-backend change memory Request and limits

build.gradle, config/owasp/suppressions.xml, src/functionalTest/java/uk/gov/hmcts/reform/pcqbackend/controllers/SasTokenControllerTest.java, src/test/java/uk/gov/hmcts/reform/pcqbackend/service/SasTokenServiceTest.java
https://tools.hmcts.net/jira/browse/PCQ-1728
Upgrade azure-storage-blob
```
[ ] Yes
[x] No
```
=> PCQ-1728 azure-storage-blob upgrade

infrastructure/main.tf
=> Enable auto grow postgres db

src/main/java/uk/gov/hmcts/reform/pcqbackend/domain/ProtectedCharacteristics.java, src/main/java/uk/gov/hmcts/reform/pcqbackend/repository/ProtectedCharacteristicsRepository.java, src/main/java/uk/gov/hmcts/reform/pcqbackend/repository/impl/ProtectedCharacteristicsRepositoryImpl.java, src/main/java/uk/gov/hmcts/reform/pcqbackend/service/SubmitAnswersService.java
https://tools.hmcts.net/jira/browse/LAU-880
submitAnswers API endpoint inserts last_updated_timestamp value
=> LAU-880 submitAnswers API inserts last updated timestamp

build.gradle, config/owasp/suppressions.xml
Removing unneeded CVE suppressions
=> Remove CVE suppressions

src/integrationTest/java/uk/gov/hmcts/reform/pcqbackend/controllers/OptOutPcqRequestIntegrationTest.java, src/main/java/uk/gov/hmcts/reform/pcqbackend/controllers/ConsolidationController.java, src/main/java/uk/gov/hmcts/reform/pcqbackend/controllers/PcqAnswersController.java, src/main/java/uk/gov/hmcts/reform/pcqbackend/controllers/SasTokenController.java, src/main/java/uk/gov/hmcts/reform/pcqbackend/service/SubmitAnswersService.java, src/main/java/uk/gov/hmcts/reform/pcqbackend/utils/ConversionUtil.java, src/test/java/uk/gov/hmcts/reform/pcqbackend/controllers/SasTokenControllerTest.java, src/test/java/uk/gov/hmcts/reform/pcqbackend/utils/ConversionUtilTest.java
LAU-880
Copy last updated timestamp from completed date
Address few sonarlint code smells
=> LAU-880 copy last updated timestamp from completed date

build.gradle, src/functionalTest/java/uk/gov/hmcts/reform/pcqbackend/controllers/PcqAnswersErrorResponseTest.java, src/functionalTest/resources/application-functional.yaml, src/main/java/uk/gov/hmcts/reform/pcqbackend/controllers/ConsolidationController.java, src/main/java/uk/gov/hmcts/reform/pcqbackend/controllers/SasTokenController.java, src/main/java/uk/gov/hmcts/reform/pcqbackend/domain/ProtectedCharacteristics.java, src/main/java/uk/gov/hmcts/reform/pcqbackend/exceptions/DataNotFoundException.java, src/main/java/uk/gov/hmcts/reform/pcqbackend/exceptions/InvalidAuthenticationException.java, src/main/java/uk/gov/hmcts/reform/pcqbackend/exceptions/InvalidRequestException.java, src/main/java/uk/gov/hmcts/reform/pcqbackend/exceptions/MigrationScriptException.java, src/main/java/uk/gov/hmcts/reform/pcqbackend/exceptions/SchemaValidationException.java, src/main/java/uk/gov/hmcts/reform/pcqbackend/exceptions/UnableToGenerateSasTokenException.java, src/main/java/uk/gov/hmcts/reform/pcqbackend/repository/ProtectedCharacteristicsRepository.java, src/main/java/uk/gov/hmcts/reform/pcqbackend/repository/ProtectedCharacteristicsRepositoryCustom.java, src/main/java/uk/gov/hmcts/reform/pcqbackend/repository/impl/ProtectedCharacteristicsRepositoryImpl.java, src/main/java/uk/gov/hmcts/reform/pcqbackend/security/JwtTokenFilter.java, src/main/java/uk/gov/hmcts/reform/pcqbackend/security/SecurityConfiguration.java, src/main/java/uk/gov/hmcts/reform/pcqbackend/service/SasTokenService.java, src/main/java/uk/gov/hmcts/reform/pcqbackend/service/SubmitAnswersService.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/pcqbackend/controllers/ConsolidationControllerTest.java, src/test/java/uk/gov/hmcts/reform/pcqbackend/controllers/PcqAnswersControllerTest.java, src/test/java/uk/gov/hmcts/reform/pcqbackend/controllers/SasTokenControllerTest.java, src/test/java/uk/gov/hmcts/reform/pcqbackend/service/AuthServiceTest.java, src/test/java/uk/gov/hmcts/reform/pcqbackend/service/ConsolidationServiceTest.java, src/test/java/uk/gov/hmcts/reform/pcqbackend/service/SasTokenServiceTest.java, src/test/java/uk/gov/hmcts/reform/pcqbackend/service/SubmitAnswersServiceTest.java
https://tools.hmcts.net/jira/browse/PCQ-1651
Address sonarcloud code smells
=> PCQ-1651 address sonarcloud code smells

src/test/java/uk/gov/hmcts/reform/pcqbackend/controllers/PcqAnswersControllerTest.java, src/test/java/uk/gov/hmcts/reform/pcqbackend/service/SubmitAnswersServiceTest.java
Missed few sonar cloud reported issues, addressing with this PR.
=> PCQ-1651 address missed code smells

src/main/resources/db/migration/V008__Schema.sql
https://tools.hmcts.net/jira/browse/LAU-882
Populate last updated timestamp field in DB
=> Lau 882 populate last updated

charts/pcq-backend/Chart.yaml, charts/pcq-backend/values.yaml, src/integrationTest/java/uk/gov/hmcts/reform/pcqbackend/service/PcqDisposerServiceIntegrationTest.java, src/main/java/uk/gov/hmcts/reform/pcqbackend/service/PcqDisposerService.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/pcqbackend/service/PcqDisposerServiceTest.java
Add explicit setting to enable/disable PCQ disposer
=> LAU-883 add explicit setting to enable/disable PCQ disposer

charts/pcq-backend/Chart.yaml, charts/pcq-backend/values.aat.template.yaml, charts/pcq-backend/values.preview.template.yaml, charts/pcq-backend/values.yaml, src/integrationTest/java/uk/gov/hmcts/reform/pcqbackend/service/PcqDisposerServiceIntegrationTest.java, src/main/java/uk/gov/hmcts/reform/pcqbackend/Application.java, src/main/java/uk/gov/hmcts/reform/pcqbackend/JobApplication.java, src/main/java/uk/gov/hmcts/reform/pcqbackend/service/PcqDisposerService.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/pcqbackend/ApplicationTest.java, src/test/java/uk/gov/hmcts/reform/pcqbackend/JobApplicationTest.java, src/test/java/uk/gov/hmcts/reform/pcqbackend/repository/impl/ProtectedCharacteristicsRepositoryImplTest.java, src/test/java/uk/gov/hmcts/reform/pcqbackend/service/PcqDisposerServiceTest.java
https://tools.hmcts.net/jira/browse/LAU-883
Enable job mode on pcq backend
=> LAU-883 enable job

src/main/resources/db/migration/V010__Schema.sql
https://tools.hmcts.net/jira/browse/LAU-884
Schema update to make last_updated_timestamp not null
=> Lau 884 set updated time not null

src/integrationTest/java/uk/gov/hmcts/reform/pcqbackend/service/PcqDisposerServiceIntegrationTest.java, src/main/java/uk/gov/hmcts/reform/pcqbackend/service/PcqDisposerService.java, src/test/java/uk/gov/hmcts/reform/pcqbackend/service/PcqDisposerServiceTest.java
https://tools.hmcts.net/jira/browse/LAU-887
Uncomment actual deletion since it should not be executed in simulation mode
=> LAU-887 enable simulation mode

audit.json
Ignore zaproxy
```
[ ] Yes
[x] No
```
=> ignore zaproxy

config/owasp/suppressions.xml
Suppress azure cve till 1st December 
```
[ ] Yes
[x] No
```
=> suppress-azure-cves

charts/pcq-backend/Chart.yaml, src/main/java/uk/gov/hmcts/reform/pcqbackend/JobApplication.java, src/test/java/uk/gov/hmcts/reform/pcqbackend/JobApplicationTest.java
https://tools.hmcts.net/jira/browse/LAU-915
Adding Exception when disposer doesn't run.
```
[ ] Yes
[x] No
```
=> LAU-915 Adding exception when PCQ Disposer doesn't run( DO NOT MERGE ONLY for testing)

src/test/java/uk/gov/hmcts/reform/pcqbackend/JobApplicationTest.java
https://tools.hmcts.net/jira/browse/LAU-915
Fix test
```
[ ] Yes
[x] No
```
=> LAU-915 fix test

Dockerfile, build.gradle
https://tools.hmcts.net/jira/browse/PCQ-1971
Java upgrade to 21
```
[ ] Yes
[x] No
```
=> PCQ-1971 java upgrade to 21

config/owasp/suppressions.xml
Remove unnecessary suppression
```
[ ] Yes
[x] No
```
=> remove-unnecessary-suppression

build.gradle
https://tools.hmcts.net/jira/browse/PCQ-1965
Upgrade Unit
```
[ ] Yes
[x] No
```
=> PCQ-1965 upgrade Unit

SECURITY.md
https://tools.hmcts.net/jira/browse/PCQ-1979
Add security.md file
```
[ ] Yes
[x] No
```
=> PCQ-1979 Create SECURITY.md

charts/pcq-backend/Chart.yaml
Bump java chart version to OCI version
```
[ ] Yes
[x] No
```
=> Bump java chart version to OCI

Jenkinsfile_CNP
https://tools.hmcts.net/jira/browse/CME-130
Disabling ITHC branch sync for DB monitoring tests
```
[ ] Yes
[x] No
```
=> CME-130 disable ithc sync for db monitoring tests

infrastructure/ithc.tfvars, infrastructure/main.tf, infrastructure/prod.tfvars, infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/CME-130
Added action group to alert on high DB usage
```
[ ] Yes
[x] No
```
=> CME-130 add db monitoring action group

Jenkinsfile_CNP, infrastructure/main.tf, infrastructure/prod.tfvars, infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/CME-130
Add prod DB monitoring
```
[ ] Yes
[x] No
```
=> CME-130 add prod db monitoring

infrastructure/sdp.tf
**Before creating a pull request make sure that:**
Please remove this line and everything above and fill the following sections:
```
[ ] Yes
[ ] No
```
=> ADD postgres flexible dependency back to sdp as suggested by platops

infrastructure/main.tf, infrastructure/prod.tfvars, infrastructure/sdp.tf, infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/PCQ-2027
Add missing reporting terraform configs
```
[ ] Yes
[x] No
```
=> Add missing reporting terraform configs
